name: Build and publish on every commit

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Checkout build script
      uses: actions/checkout@v4

    - name: Checkout kernel source
      uses: actions/checkout@v4
      with:
        repository: 'jhovold/linux'
        ref: 'wip/x1e80100-6.14-rc4'
        path: 'kernel' 

    - name: Build
      run: ./build.sh
      shell: bash

    - name: List everything
      run: find . -iname "*.deb"
      shell: bash

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "devbuild"
        prerelease: true
        title: "Development Build"
        files: |
          *.deb
